# Problem 2
#
# Each new term in the Fibonacci sequence is generated by adding the previous 
# two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.


fibonacci = [1,2]

a = 1
b = 2

while a + b < 4_000_000:
    c = a + b
    fibonacci.append(c)
    a = b
    b = c

#print(fibonacci)
sum = 0

for num in fibonacci:
    if num % 2 == 0:
        sum += num

print(sum)